import re

__all__ = ['get_gfrogs_dict_keys_list', 'get_formatted_values_by_keys', 'extract_and_filter_qa_with_buffer', 'scan_for_error_sprogs', 'clean_ocrd_text']

gfrogs_dict = {
    "1.1": "State the name, ADDRESS, telephone number, and relationship to you of each PERSON who prepared or assisted in the preparation of the responses to these interrogatories. (Do not identify anyone who simply typed or reproduced the responses.)",
    "2.1": "State:\n\t(a)\tyour name;\n\t(b)\tevery name you have used in the past; and\n\t(c)\tthe dates you used each name.",
    "2.2": "State the date and place of your birth.",
    "2.3": "At the time of the INCIDENT, did you have a driver's license? If so state:\n\t(a)\tthe state or other issuing entity;\n\t(b)\tthe license number and type;\n\t(c)\tthe date of issuance; and\n\t(d)\tall restrictions.",
    "2.4": "At the time of the INCIDENT, did you have any other permit or license for the operation of a motor vehicle? If so, state:\n\t(a)\tthe state or other issuing entity;\n\t(b)\tthe license number and type;\n\t(c)\tthe date of issuance; and\n\t(d)\tall restrictions.",
    "2.5": "State:\n\t(a)\tyour present residence ADDRESS;\n\t(b)\tyour residence ADDRESSES for the past five years; and\n\t(c)\tthe dates you lived at each ADDRESS.",
    "2.6": "State:\n\t(a)\tthe name, ADDRESS, and telephone number of your present employer or place of self-employment; and\n\t(b)\tthe name, ADDRESS, dates of employment, job title, and nature of work for each employer or self-employment you have had from five years before the INCIDENT until today.",
    "2.7": "State:\n\t(a)\tthe name and ADDRESS of each school or other academic or vocational institution you have attended, beginning with high school;\n\t(b)\tthe dates you attended;\n\t(c)\tthe highest grade level you have completed; and\n\t(d)\tthe degrees received.",
    "2.8": "Have you ever been convicted of a felony? If so, for each conviction state:\n\t(a)\tthe city and state where you were convicted;\n\t(b)\tthe date of conviction;\n\t(c)\tthe offense; and\n\t(d)\tthe court and case number.",
    "2.9": "Can you speak English with ease? If not, what language and dialect do you normally use?",
    "2.10": "Can you read and write English with ease? If not, what language and dialect do you normally use?",
    "2.11": "At the time of the INCIDENT were you acting as an agent or employee for any PERSON? If so, state:\n\t(a)\tthe name, ADDRESS, and telephone number of that PERSON; and\n\t(b)\ta description of your duties.",
    "2.12": "At the time of the INCIDENT did you or any other person have any physical, emotional, or mental disability or condition that may have contributed to the occurrence of the INCIDENT? If so, for each person state:\n\t(a)\tthe name, ADDRESS, and telephone number;\n\t(b)\tthe nature of the disability or condition; and\n\t(c)\tthe manner in which the disability or condition contributed to the occurrence of the INCIDENT.",
    "2.13": "Within 24 hours before the INCIDENT did you or any person involved in the INCIDENT use or take any of the following substances: alcoholic beverage, marijuana, or other drug or medication of any kind (prescription or not)? If so, for each person state:\n\t(a)\tthe name, ADDRESS, and telephone number;\n\t(b)\tthe nature or description of each substance;\n\t(c)\tthe quantity of each substance used or taken;\n\t(d)\tthe date and time of day when each substance was used or taken;\n\t(e)\tthe ADDRESS where each substance was used or taken;\n\t(f)\tthe name, ADDRESS, and telephone number of each person who was present when each substance was used or taken; and\n\t(g)\tthe name, ADDRESS, and telephone number of any HEALTH CARE PROVIDER who prescribed or furnished the substance and the condition for which it was prescribed or furnished.",
    "3.1": "Are you a corporation? If so, state:\n\t(a)\tthe name stated in the current articles of incorporation;\n\t(b)\tall other names used by the corporation during the past 10 years and the dates each was used;\n\t(c)\tthe date and place of incorporation;\n\t(d)\tthe ADDRESS of the principal place of business; and\n\t(e)\twhether you are qualified to do business in California.",
    "3.2": "Are you a partnership? If so, state:\n\t(a)\tthe current partnership name;\n\t(b)\tall other names used by the partnership during the past 10 years and the dates each was used;\n\t(c)\twhether you are a limited partnership and, if so, under the laws of what jurisdiction;\n\t(d)\tthe name and ADDRESS of each general partner; and\n\t(e)\tthe ADDRESS of the principal place of business.",
    "3.3": "Are you a limited liability company? If so, state:\n\t(a)\tthe name stated in the current articles of organization;\n\t(b)\tall other names used by the company during the past 10 years and the date each was used;\n\t(c)\tthe date and place of filing of the articles of organization;\n\t(d)\tthe ADDRESS of the principal place of business; and\n\t(e)\twhether you are qualified to do business in California.",
    "3.4": "Are you a joint venture? If so, state:\n\t(a)\tthe current joint venture name;\n\t(b)\tall other names used by the joint venture during the past 10 years and the dates each was used;\n\t(c)\tthe name and ADDRESS of each joint venturer; and\n\t(d)\tthe ADDRESS of the principal place of business.",
    "3.5": "Are you an unincorporated association? If so, state:\n\t(a)\tthe current unincorporated association name;\n\t(b)\tall other names used by the unincorporated association during the past 10 years and the dates each was used; and\n\t(c)\tthe ADDRESS of the principal place of business.",
    "3.6": "Have you done business under a fictitious name during the past 10 years? If so, for each fictitious name state:\n\t(a)\tthe name;\n\t(b)\tthe dates each was used;\n\t(c)\tthe state and county of each fictitious name filing; and\n\t(d)\tthe ADDRESS of the principal place of business.",
    "3.7": "Within the past five years has any public entity registered or licensed your business? If so, for each license or registration:\n\t(a)\tidentify the license or registration;\n\t(b)\tstate the name of the public entity; and\n\t(c)\tstate the dates of issuance and expiration.",
    "4.1": "At the time of the INCIDENT, was there in effect any policy of insurance through which you were or might be insured in any manner (for example, primary, pro-rata, or excess liability coverage or medical expense coverage) for the damages, claims, or actions that have arisen out of the INCIDENT? If so, for each policy state:\n\t(a)\tthe kind of coverage;\n\t(b)\tthe name and ADDRESS of the insurance company;\n\t(c)\tthe name, ADDRESS, and telephone number of each named insured;\n\t(d)\tthe policy number;\n\t(e)\tthe limits of coverage for each type of coverage contained in the policy;\n\t(f)\twhether any reservation of rights or controversy or coverage dispute exists between you and the insurance company; and\n\t(g)\tthe name, ADDRESS, and telephone number of the custodian of the policy.",
    "4.2": "Are you self-insured under any statute for the damages, claims, or actions that have arisen out of the INCIDENT? If so, specify the statute.",
    "6.1": "Do you attribute any physical, mental, or emotional injuries to the INCIDENT? (If your answer is “no,” do not answer interrogatories 6.2 through 6.7).",
    "6.2": "Identify each injury you attribute to the INCIDENT and the area of your body affected.",
    "6.3": "Do you still have any complaints that you attribute to the INCIDENT? If so, for each complaint state:\n\t(a)\ta description;\n\t(b)\twhether the complaint is subsiding, remaining the same, or becoming worse; and\n\t(c)\tthe frequency and duration.",
    "6.4": "Did you receive any consultation or examination (except from expert witnesses covered by Code of Civil Procedure sections 2034.210–2034.310) or treatment from a HEALTH CARE PROVIDER for any injury you attribute to the INCIDENT? If so, for each HEALTH CARE PROVIDER state:\n\t(a)\tthe name, ADDRESS, and telephone number;\n\t(b)\tthe type of consultation, examination, or treatment provided;\n\t(c)\tthe dates you received consultation, examination, or treatment; and\n\t(d)\tthe charges to date.",
    "6.5": "Have you taken any medication, prescribed or not, as a result of injuries that you attribute to the INCIDENT? If so, for each medication state:\n\t(a)\tthe name;\n\t(b)\tthe PERSON who prescribed or furnished it;\n\t(c)\tthe date it was prescribed or furnished;\n\t(d)\tthe dates you began and stopped taking it; and\n\t(e)\tthe cost to date.",
    "6.6": "Are there any other medical services necessitated by the injuries that you attribute to the INCIDENT that were not previously listed (for example, ambulance, nursing, prosthetics)? If so, for each service state:\n\t(a)\tthe nature;\n\t(b)\tthe date;\n\t(c)\tthe cost; and\n\t(d)\tthe name, ADDRESS, and telephone number of each provider.",
    "6.7": "Has any HEALTH CARE PROVIDER advised that you may require future or additional treatment for any injuries that you attribute to the INCIDENT? If so, for each injury state:\n\t(a)\tthe name and ADDRESS of each HEALTH CARE PROVIDER;\n\t(b)\tthe complaints for which the treatment was advised; and\n\t(c)\tthe nature, duration, and estimated cost of the treatment.",
    "7.1": "Do you attribute any loss of or damage to a vehicle or other property to the INCIDENT? If so, for each item of property:\n\t(a)\tdescribe the property;\n\t(b)\tdescribe the nature and location of the damage to the property;\n\t(c)\tstate the amount of damage you are claiming for each item of property and how the amount was calculated; and\n\t(d)\tif the property was sold, state the name, ADDRESS, and telephone number of the seller, the date of sale, and the sale price.",
    "7.2": "Has a written estimate or evaluation been made for any item of property referred to in your answer to the preceding interrogatory? If so, for each estimate or evaluation state:\n\t(a)\tthe name, ADDRESS, and telephone number of the PERSON who prepared it and the date prepared;\n\t(b)\tthe name, ADDRESS, and telephone number of each PERSON who has a copy of it; and\n\t(c)\tthe amount of damage stated.",
    "7.3": "Has any item of property referred to in your answer to interrogatory 7.1 been repaired? If so, for each item state:\n\t(a)\tthe date repaired;\n\t(b)\ta description of the repair;\n\t(c)\tthe repair cost;\n\t(d)\tthe name, ADDRESS, and telephone number of the PERSON who repaired it;\n\t(e)\tthe name, ADDRESS, and telephone number of the PERSON who paid for the repair.",
    "8.1": "Do you attribute any loss of income or earning capacity to the INCIDENT? (If your answer is “no,” do not answer interrogatories 8.2 through 8.8).",
    "8.2": "State:\n\t(a)\tthe nature of your work;\n\t(b)\tyour job title at the time of the INCIDENT; and\n\t(c)\tthe date your employment began.",
    "8.3": "State the last date before the INCIDENT that you worked for compensation.",
    "8.4": "State your monthly income at the time of the INCIDENT and how the amount was calculated.",
    "8.5": "State the date you returned to work at each place of employment following the INCIDENT.",
    "8.6": "State the dates you did not work and for which you lost income as a result of the INCIDENT.",
    "8.7": "State the total income you have lost to date as a result of the INCIDENT and how the amount was calculated.",
    "8.8": "Will you lose income in the future as a result of the INCIDENT? If so, state:\n\t(a)\tthe facts upon which you base this contention;\n\t(b)\tan estimate of the amount;\n\t(c)\tan estimate of how long you will be unable to work; and\n\t(d)\thow the claim for future income is calculated.",
    "9.1": "Are there any other damages that you attribute to the INCIDENT? If so, for each item of damage state:\n\t(a)\tthe nature;\n\t(b)\tthe date it occurred;\n\t(c)\tthe amount; and\n\t(d)\tthe name, ADDRESS, and telephone number of each PERSON to whom an obligation was incurred.",
    "9.2": "Do any DOCUMENTS support the existence or amount of any item of damages claimed in interrogatory 9.1? If so, describe each document and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT.",
    "10.1": "At any time before the INCIDENT did you have complaints or injuries that involved the same part of your body claimed to have been injured in the INCIDENT? If so, for each state:\n\t(a)\ta description of the complaint or injury;\n\t(b)\tthe dates it began and ended; and\n\t(c)\tthe name, ADDRESS, and telephone number of each HEALTH CARE PROVIDER whom you consulted or who examined or treated you.",
    "10.2": "List all physical, mental, and emotional disabilities you had immediately before the INCIDENT. (You may omit mental or emotional disabilities unless you attribute any mental or emotional injury to the INCIDENT. )",
    "10.3": "At any time after the INCIDENT, did you sustain injuries of the kind for which you are now claiming damages? If so, for each incident giving rise to an injury state:\n\t(a)\tthe date and the place it occurred;\n\t(b)\tthe name, ADDRESS, and telephone number of any other PERSON involved;\n\t(c)\tthe nature of any injuries you sustained;\n\t(d)\tthe name, ADDRESS, and telephone number of each HEALTH CARE PROVIDER who you consulted or who examined or treated you; and\n\t(e)\tthe nature of the treatment and its duration.",
    "11.1": "Except for this action, in the past 10 years have you filed an action or made a written claim or demand for compensation for your personal injuries? If so, for each action, claim, or demand state:\n\t(a)\tthe date, time, and place and location (closest street ADDRESS or intersection) of the INCIDENT giving rise to the action, claim, or demand;\n\t(b)\tthe name, ADDRESS, and telephone number of each PERSON against whom the claim or demand was made or the action filed;\n\t(c)\tthe court, names of the parties, and case number of any action filed;\n\t(d)\tthe name, ADDRESS, and telephone number of any attorney representing you;\n\t(e)\twhether the claim or action has been resolved or is pending; and\n\t(f)\ta description of the injury.",
    "11.2": "In the past 10 years have you made a written claim or demand for workers' compensation benefits? If so, for each claim or demand state:\n\t(a)\tthe date, time, and place of the INCIDENT giving rise to the claim;\n\t(b)\tthe name, ADDRESS, and telephone number of your employer at the time of the injury;\n\t(c)\tthe name, ADDRESS, and telephone number of the workers’ compensation insurer and the claim number;\n\t(d)\tthe period of time during which you received workers’ compensation benefits;\n\t(e)\ta description of the injury;\n\t(f)\tthe name, ADDRESS, and telephone number of any HEALTH CARE PROVIDER who provided services; and\n\t(g)\tthe case number at the Workers’ Compensation Appeals Board.",
    "12.1": "State the name, ADDRESS, and telephone number of each individual:\n\t(a)\twho witnessed the INCIDENT or the events occurring immediately before or after the INCIDENT;\n\t(b)\twho made any statement at the scene of the INCIDENT;\n\t(c)\twho heard any statements made about the INCIDENT by any individual at the scene; and\n\t(d)\twho YOU OR ANYONE ACTING ON YOUR BEHALF claim has knowledge of the INCIDENT (except for expert witnesses covered by Code of Civil Procedure section 2034).",
    "12.2": "Have YOU OR ANYONE ACTING ON YOUR BEHALF interviewed any individual concerning the INCIDENT? If so, for each individual state:\n\t(a)\tthe name, ADDRESS, and telephone number of the individual interviewed;\n\t(b)\tthe date of the interview; and\n\t(c)\tthe name, ADDRESS, and telephone number of the PERSON who conducted the interview.",
    "12.3": "Have YOU OR ANYONE ACTING ON YOUR BEHALF obtained a written or recorded statement from any individual concerning the INCIDENT? If so, for each statement state:\n\t(a)\tthe name, ADDRESS, and telephone number of the individual from whom the statement was obtained;\n\t(b)\tthe name, ADDRESS, and telephone number of the individual who obtained the statement;\n\t(c)\tthe date the statement was obtained; and\n\t(d)\tthe name, ADDRESS, and telephone number of each PERSON who has the original statement or a copy.",
    "12.4": "Do YOU OR ANYONE ACTING ON YOUR BEHALF know of any photographs, films, or videotapes depicting any place, object, or individual concerning the INCIDENT or plaintiff's injuries? If so, state:\n\t(a)\tthe number of photographs or feet of film or videotape;\n\t(b)\tthe places, objects, or persons photographed, filmed, or videotaped;\n\t(c)\tthe date the photographs, films, or videotapes were taken;\n\t(d)\tthe name, ADDRESS, and telephone number of the individual taking the photographs, films, or videotapes; and\n\t(e)\tthe name, ADDRESS, and telephone number of each PERSON who has the original or a copy of the photographs, films, or videotapes.",
    "12.5": "Do YOU OR ANYONE ACTING ON YOUR BEHALF know of any diagram, reproduction, or model of any place or thing (except for items developed by expert witnesses covered by Code of Civil Procedure sections 2034.210–2034.310) concerning the INCIDENT? If so, for each item state:\n\t(a)\tthe type (i.e., diagram, reproduction, or model);\n\t(b)\tthe subject matter; and\n\t(c)\tthe name, ADDRESS, and telephone number of each PERSON who has it.",
    "12.6": "Was a report made by any PERSON concerning the INCIDENT? If so, state:\n\t(a)\tthe name, title, identification number, and employer of the PERSON who made the report;\n\t(b)\tthe date and type of report made;\n\t(c)\tthe name, ADDRESS, and telephone number of the PERSON for whom the report was made; and\n\t(d)\tthe name, ADDRESS, and telephone number of each PERSON who has the original or a copy of the report.",
    "12.7": "Have YOU OR ANYONE ACTING ON YOUR BEHALF inspected the scene of the INCIDENT? If so, for each inspection state:\n\t(a)\tthe name, ADDRESS, and telephone number of the individual making the inspection (except for expert witnesses covered by Code of Civil Procedure sections 2034.210–2034.310); and\n\t(b)\tthe date of the inspection.",
    "13.1": "Have YOU OR ANYONE ACTING ON YOUR BEHALF conducted surveillance of any individual involved in the INCIDENT or any party to this action? If so, for each surveillance state:\n\t(a)\tthe name, ADDRESS, and telephone number of the individual or party;\n\t(b)\tthe time, date, and place of the surveillance;\n\t(c)\tthe name, ADDRESS, and telephone number of the individual who conducted the surveillance; and\n\t(d)\tthe name, ADDRESS, and telephone number of each PERSON who has the original or a copy of any surveillance photograph, film, or videotape.",
    "13.2": "Has a written report been prepared on the surveillance? If so, for each written report state:\n\t(a)\tthe title;\n\t(b)\tthe date;\n\t(c)\tthe name, ADDRESS, and telephone number of the individual who prepared the report; and\n\t(d)\tthe name, ADDRESS, and telephone number of each PERSON who has the original or a copy.",
    "14.1": "Do YOU OR ANYONE ACTING ON YOUR BEHALF contend that any PERSON involved in the INCIDENT violated any statute, ordinance, or regulation and that the violation was a legal (proximate) cause of the INCIDENT? If so, identify the name, ADDRESS, and telephone number of each PERSON and the statute, ordinance, or regulation that was violated.",
    "14.2": "Was any PERSON cited or charged with a violation of any statute, ordinance, or regulation as a result of this INCIDENT? If so, for each PERSON state:\n\t(a)\tthe name, ADDRESS, and telephone number of the PERSON;\n\t(b)\tthe statute, ordinance, or regulation allegedly violated;\n\t(c)\twhether the PERSON entered a plea in response to the citation or charge and, if so, the plea entered; and\n\t(d)\tthe name and ADDRESS of the court or administrative agency, names of the parties, and case number.",
    "15.1": "Identify each denial of a material allegation and each special or affirmative defense in your pleadings and for each:\n\t(a)\tstate all facts upon which you base the denial or special or affirmative defense;\n\t(b)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of those facts; and\n\t(c)\tidentify all DOCUMENTS and other tangible things that support your denial or special or affirmative defense, and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT.",
    "16.1": "Do you contend that any PERSON, other than you or plaintiff, contributed to the occurrence of the INCIDENT or the injuries or damages claimed by plaintiff? If so, for each PERSON:\n\t(a)\tstate the name, ADDRESS, and telephone number of the PERSON;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.2": "Do you contend that plaintiff was not injured in the INCIDENT? If so:\n\t(a)\tstate all facts upon which you base your contention;\n\t(b)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(c)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing",
    "16.3": "Do you contend that the injuries or the extent of the injuries claimed by plaintiff as disclosed in discovery proceedings thus far in this case were not caused by the INCIDENT? If so, for each injury:\n\t(a)\tidentify it;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.4": "Do you contend that any of the services furnished by any HEALTH CARE PROVIDER claimed by plaintiff in discovery proceedings thus far in this case were not due to the INCIDENT? If so:\n\t(a)\tidentify each service;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.5": "Do you contend that any of the costs of services furnished by any HEALTH CARE PROVIDER claimed as damages by plaintiff in discovery proceedings thus far in this case were not necessary or unreasonable? If so:\n\t(a)\tidentify each cost;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.6": "Do you contend that any part of the loss of earnings or income claimed by plaintiff in discovery proceedings thus far in this case was unreasonable or was not caused by the INCIDENT? If so:\n\t(a)\tidentify each part of the loss;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.7": "Do you contend that any of the property damage claimed by plaintiff in discovery Proceedings thus far in this case was not caused by the INCIDENT? If so:\n\t(a)\tidentify each item of property damage;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.8": "Do you contend that any of the costs of repairing the property damage claimed by plaintiff in discovery proceedings thus far in this case were unreasonable? If so:\n\t(a)\tidentify each cost item;\n\t(b)\tstate all facts upon which you base your contention;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of the facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your contention and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "16.9": "Do YOU OR ANYONE ACTING ON YOUR BEHALF have any DOCUMENT (for example, insurance bureau index reports) concerning claims for personal injuries made before or after the INCIDENT by a plaintiff in this case? If so, for each plaintiff state:\n\t(a)\tthe source of each DOCUMENT;\n\t(b)\tthe date each claim arose;\n\t(c)\tthe nature of each claim; and\n\t(d)\tthe name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT.",
    "16.10": "Do YOU OR ANYONE ACTING ON YOUR BEHALF have any DOCUMENT concerning the past or present physical, mental, or emotional condition of any plaintiff in this case from a HEALTH CARE PROVIDER not previously identified (except for expert witnesses covered by Code of Civil Procedure sections 2034.210–2034.310)? If so, for each plaintiff state:\n\t(a)\tthe name, ADDRESS, and telephone number of each HEALTH CARE PROVIDER;\n\t(b)\ta description of each DOCUMENT; and\n\t(c)\tthe name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT.",
    "17.1": "Is your response to each request for admission served with these interrogatories an unqualified admission? If not, for each response that is not an unqualified admission:\n\t(a)\tstate the number of the request;\n\t(b)\tstate all facts upon which you base your response;\n\t(c)\tstate the names, ADDRESSES, and telephone numbers of all PERSONS who have knowledge of those facts; and\n\t(d)\tidentify all DOCUMENTS and other tangible things that support your response and state the name, ADDRESS, and telephone number of the PERSON who has each DOCUMENT or thing.",
    "20.1": "State the date, time, and place of the INCIDENT (closest street ADDRESS or intersection).",
    "20.2": "For each vehicle involved in the INCIDENT, state:\n\t(a)\tthe year, make, model, and license number;\n\t(b)\tthe name, ADDRESS, and telephone number of the driver;\n\t(c)\tthe name, ADDRESS, and telephone number of each occupant other than the driver;\n\t(d)\tthe name, ADDRESS, and telephone number of each registered owner;\n\t(e)\tthe name, ADDRESS, and telephone number of each lessee;\n\t(f)\tthe name, ADDRESS, and telephone number of each owner other than the registered owner or lien holder; and\n\t(g)\tthe name of each owner who gave permission or consent to the driver to operate the vehicle.",
    "20.3": "State the ADDRESS and location where your trip began and the ADDRESS and location of your destination.",
    "20.4": "Describe the route that you followed from the beginning of your trip to the location of the INCIDENT, and state the location of each stop, other than routine traffic stops, during the trip leading up to the INCIDENT.",
    "20.5": "State the name of the street or roadway, the lane of travel, and the direction of travel of each vehicle involved in the INCIDENT for the 500 feet of travel before the INCIDENT.",
    "20.6": "Did the INCIDENT occur at an intersection? If so, describe all traffic control devices, signals, or signs at the intersection.",
    "20.7": "Was there a traffic signal facing you at the time of the INCIDENT? If so, state:\n\t(a)\tyour location when you first saw it;\n\t(b)\tthe color;\n\t(c)\tthe number of seconds it had been that color; and\n\t(d)\twhether the color changed between the time you first saw it and the INCIDENT.",
    "20.8": "State how the INCIDENT occurred, giving the speed, direction, and location of each vehicle involved:\n\t(a)\tjust before the INCIDENT;\n\t(b)\tat the time of the INCIDENT; and\n\t(c)\tjust after the INCIDENT.",
    "20.9": "Do you have information that a malfunction or defect in a vehicle caused the INCIDENT? If so:\n\t(a)\tidentify the vehicle;\n\t(b)\tidentify each malfunction or defect;\n\t(c)\tstate the name, ADDRESS, and telephone number of each PERSON who is a witness to or has information about each malfunction or defect; and\n\t(d)\tstate the name, ADDRESS, and telephone number of each PERSON who has custody of each defective part.",
    "20.10": "Do you have information that any malfunction or defect in a vehicle contributed to the injuries sustained in the INCIDENT? If so:\n\t(a)\tidentify the vehicle;\n\t(b)\tidentify each malfunction or defect;\n\t(c)\tstate the name, ADDRESS, and telephone number of each PERSON who is a witness to or has information about each malfunction or defect; and\n\t(d)\tstate the name, ADDRESS, and telephone number of each PERSON who has custody of each defective part.",
    "20.11": "State the name, ADDRESS, and telephone number of each owner and each PERSON who has had possession since the INCIDENT of each vehicle involved in the INCIDENT.",
    "50.1": "For each agreement alleged in the pleadings:\n\t(a)\tidentify each DOCUMENT that is part of the agreement and for each state the name, ADDRESS, and telephone number of each PERSON who has the DOCUMENT;\n\t(b)\tstate each part of the agreement not in writing, the name, ADDRESS, and telephone number of each PERSON agreeing to that provision, and the date that part of the agreement was made;\n\t(c)\tidentify all DOCUMENTS that evidence any part of the agreement not in writing and for each state the name, ADDRESS, and telephone number of each PERSON who has the DOCUMENT;\n\t(d)\tidentify all DOCUMENTS that are part of any modification to the agreement, and for each state the name, ADDRESS, and telephone number of each PERSON who has the DOCUMENT;\n\t(e)\tstate each modification not in writing, the date, and the name, ADDRESS, and telephone number of each PERSON agreeing to the modification, and the date the modification was made;\n\t(f)\tidentify all DOCUMENTS that evidence any modification of the agreement not in writing and for each state the name, ADDRESS, and telephone number of each PERSON who has the DOCUMENT.",
    "50.2": "Was there a breach of any agreement alleged in the pleadings? If so, for each breach describe and give the date of every act or omission that you claim is the breach of the agreement.",
    "50.3": "Was performance of any agreement alleged in the pleadings excused? If so, identify each agreement excused and state why performance was excused.",
    "50.4": "Was any agreement alleged in the pleadings terminated by mutual agreement, release, accord and satisfaction, or novation? If so, identify each agreement terminated, the date of termination, and the basis of the termination.",
    "50.5": "Is any agreement alleged in the pleadings unenforceable? If so, identify each unenforceable agreement and state why it is unenforceable.",
    "50.6": "Is any agreement alleged in the pleadings ambiguous? If so, identify each ambiguous agreement and state why it is ambiguous.",
}

gen_frogs_definitions = {'INCIDENT': 'includes the circumstances and events surrounding the alleged accident, injury, or other occurrence or breach of contract giving rise to this action or proceeding','YOU OR ANYONE ACTING ON YOUR BEHALF': 'includes you, your agents, your employees, your insurance companies, their agents, their employees, your attorneys, your accountants, your investigators, and anyone else acting on your behalf', 'PERSON': 'includes a natural person, firm, association, organization, partnership, business, trust, limited liability company, corporation, or public entity', 'DOCUMENT': 'means a writing, as defined in Evidence Code section 250, and includes the original or a copy of handwriting, typewriting, printing, photostats, photographs, electronically stored information, and every other means of recording upon any tangible thing and form of communicating or representation, including letters, words, pictures, sounds, or symbols, or combinations of them', 'HEALTH CARE PROVIDER': 'includes any PERSON referred to in Code of Civil Procedure section 667.7(e)(3)', 'ADDRESS': 'means the street address, including the city, state, and zip code'}

def get_gfrogs_dict_keys_list():
    return gfrogs_dict.keys()

def get_formatted_values_by_keys(keys):
    """Retrieve formatted values for the specific chosen keys."""
    formatted_values = [f"Form Interrogatory No. **{key}**:[BR]{gfrogs_dict.get(key)}" for key in keys]
    return "[BR][BR]".join(formatted_values)
  
def extract_and_filter_qa_with_buffer(gfrogs_served_no_index, responses_clean_text_no_index):
    """
    Extracts and filters question and answer pairs from OCR'd text, using a buffer for unrecognized questions.
    
    PARAMETERS ARE JUST PLACEHOLDERS! THE ARGUMENTS ARE THE ONES THAT WILL BE INDEXED VARIABLES ( E.G., methods[i].gfrogs_served)!!!
    
    Args:
      gfrogs_served (list): A list of question numbers (as strings) that were actually asked.
      responses_clean_text (string): A 'cleaned' text string returned from OCR.
        
    Returns:
      dict: A dictionary containing the filtered question and answer pairs. 
    """
  
    # Regex pattern for extracting question and answer pairs
    pattern = r'(?:response|answer|objection)s?\s{1,2}to\s{1,2}(?:special |general |form |general form )?interrogator(?:y|ies)\s{1,2}(?:no\.?:?|#|number)?\W*(\d{1,3}\.\d{1,2}|\d{1,3})[-:;.\s]+(\(\w.*?|.*?)(?=\n\d+\.\s+[A-Z]|\n\n[!@#%^&*)\/\\{}_\-=+\]|<>?.]|\s+(?:FORM |RESPONSE |SPECIAL )INTERROGATORY No[\d\., ]{1,7}[-:;.\s]+|\n{4,}|\.\n{3,})'
    
    # Execute the regex to find all matches in the OCR'd text
    matches = re.findall(pattern, responses_clean_text_no_index, re.DOTALL | re.MULTILINE | re.IGNORECASE)
    
    # Initialize a dictionary with nested dictionaries for each question in gfrogs_served
    qa_dict2 = {q: {'question': gfrogs_dict.get(q, 'Question not detected/extracted'), 'answer': 'Answer not detected/extracted'} for q in gfrogs_served_no_index}
    
    # Initialize a buffer to hold answers for unrecognized questions
    buffer = []
    
    for match in matches:
      question_number = match[0]
      answer = clean_ocrd_text(match[1])
      
      # Update the answer in qa_dict only if the question is in gfrogs_served, else add to buffer
      if question_number in gfrogs_served_no_index:
        qa_dict2[question_number]['answer'] = answer
      else:
        buffer.append(answer)
    
    # Assign buffered answers to the lowest numbered questions lacking an answer
    for q in gfrogs_served_no_index:
      if qa_dict2[q]['answer'] == 'Answer not detected/extracted' and buffer:
        qa_dict2[q]['answer'] = buffer.pop(0)
          
    return qa_dict2
  
def scan_for_error_sprogs(qa_dict):
  error_sprogs = []
  # Check the qa_dict for any question or answer that was not overwritten
  for number, item in qa_dict.items():
    if item['question'] == 'Question not detected/extracted' or item['answer'] == 'Answer not detected/extracted':
      error_sprogs.append(number)
  # error_sprogs will contain the numbers for which either the question or the answer was not detected/extracted
  return error_sprogs

def clean_ocrd_text(ocrd_text):
  # Step 1: Replace qualifying newlines with a pound sign
  intermediate_text = re.sub(r'([A-Za-z][.?!\'\"\];:)]{1,4}\s)\n', r'\1£', ocrd_text)
    
  # Step 2: Remove or keep the pound sign and newline based on the following text
  regex_remove_or_keep_newline = r'£\n?(?=[ \t]*\([a-z]\)[ \t]*|\([0-9]{1,2}\)|[0-9]{1,2}\.)|£'
  intermediate_text = re.sub(regex_remove_or_keep_newline, lambda m: '\n' if m.group() == '£\n' else ' ', intermediate_text)

  # Step 3: Convert extraneous newlines to a single space
  # Target newlines preceded by words, a space, or midsentence punctuation like a comma or dash
  # and followed by words.
  intermediate_text = re.sub(r'([A-Za-z\s,\-])\n([A-Za-z])', r'\1 \2', intermediate_text)
    
  # Step 4: Replace two or more whitespace characters with a single space
  clean_text = re.sub(r'\s{2,}', ' ', intermediate_text).strip()
    
  return clean_text